# -*- coding: utf-8 -*-
"""KFold(iris).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qFxLB3D-6iA9h0PtDyQoHbK9KeXjEAce
"""

# K-Fold cross validation 기능 연습
import numpy as np
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, KFold

iris = load_iris()

x_train, x_test, y_train, y_test = train_test_split(iris['data'], iris['target'], test_size = 0.2)

# 5-fold를 구성한다. #split은 5개의 구역을 의미하면 역수 취해서 20%로 나눔을 의미함.
#이를 교차검증이라고 하며 depth=1,2,3,4,5,.... 늘리면서 구하고 각 스코어를 이용하여 평균내서 비교함.
# 총 연산횟수 => depth*5(split수)  임
cv = KFold(n_splits = 5, shuffle=True) 

depth_acc = []  # depth 별 정확도 리스트
for depth in range(1, 20):
    model = DecisionTreeClassifier(max_depth = depth)

    fold_acc = [] # k-fold 별 정확도 리스트
    for tx, vx in cv.split(x_train):  #train, eval 나누기
        # 학습용, 평가용 데이터
        xf_train, xf_eval = x_train[tx], x_train[vx]
        yf_train, yf_eval = y_train[tx], y_train[vx]

        # 학습
        model.fit(xf_train, yf_train)

        # 평가
        fold_acc.append(model.score(xf_eval, yf_eval))

    print("depth-{:2d} : fold acculate = {}".format(depth, np.round(fold_acc, 3)), end="")

    # fold 별 정확도 평균을 저장한다 = depth 별 정확도
    depth_acc.append(np.mean(fold_acc))
    print(" --> 평균 = {:.4f}".format(depth_acc[-1]))

# 최적 depth로 model를 최종 학습하고, 시험 데이터로 성능을 평가한다.
opt_depth = np.argmax(depth_acc) + 1

model = DecisionTreeClassifier(max_depth = opt_depth)
model.fit(x_train, y_train)

print("\n최적 depth = {}".format(opt_depth))
print("시험 데이터 정확도 = {:.4f}".format(model.score(x_test, y_test)))






