use jsp;


CREATE TABLE MEMBER(
ID NVARCHAR(50),
PWD NVARCHAR(50),
NAME NVARCHAR(50),
GENDER NCHAR(2),
BIRTHDAY CHAR(10),
PHONE CHAR(13),
REGDATE DATE,
EMAIL VARCHAR(200)
);

INSERT INTO MEMBER VALUES('gnjgnjgjn', '1234','홍씨', '남자','000','000', sysdate(),'g@naver.com');
INSERT INTO MEMBER VALUES('gnjg', '1234','김씨', '여자','000','000', sysdate(),'g12@naver.com');
INSERT INTO MEMBER VALUES('gkkkn', '1234','이씨', '남자','000','000', sysdate(),'g23@naver.com');

select * from member;

CREATE TABLE NOTICE(
ID INT AUTO_INCREMENT PRIMARY KEY,
TITLE NVARCHAR(100),
WRITER_ID NVARCHAR(50),
CONTENT longtext,
REGDATE TIMESTAMP,
HIT INT,
FILES NVARCHAR(1000),
PUB TINYINT
);

INSERT INTO NOTICE(TITLE, WRITER_ID, CONTENT,FILES) VALUES('제목', 'ID','DDDDD', '');

UPDATE NOTICE SET TITLE = '제목변경', CONTENT = '변경' WHERE ID = 2;

SELECT * FROM NOTICE;





CREATE TABLE COMMENT(
ID INT AUTO_INCREMENT PRIMARY KEY,
CONTTENT NVARCHAR(1000),
REGDATE TIMESTAMP,
WRTIER_ID NVARCHAR(50),
NOTICE_ID INT
);


CREATE TABLE ROLE(
ID VARCHAR(50),
DISCRIPTION NVARCHAR(500)
);

CREATE TABLE MEMBER_ROLE(
MEMBER_ID NVARCHAR(50),
ROLE_ID VARCHAR(50)
);








