
-- 하나의 테이블을 만들고 이를 연결하고 설정한 열의 이름을 기준으로 출력


SELECT ID, NAME, P.HOST_ID
FROM PLACES AS P
INNER JOIN (SELECT HOST_ID, COUNT(HOST_ID) AS C FROM PLACES GROUP BY HOST_ID) AS V ON P.HOST_ID = V.HOST_ID
WHERE V.C >= 2
ORDER BY ID