SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O
LEFT OUTER JOIN ANIMAL_INS AS I ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.INTAKE_CONDITION IS NULL         -- out 조인(연결)을 해서 없는(null) 데이터를 조회
ORDER BY ANIMAL_ID