

-- MILK가 있는 ID, YOGURT가 있는 ID를 구하고 교집합으로 구함


SELECT M.CART_ID FROM 
    (SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'MILK'
    GROUP BY CART_ID) AS M,
    (SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
    GROUP BY CART_ID) AS Y
    
WHERE M.CART_ID = Y.CART_ID
ORDER BY M.CART_ID



-- CROSS JOIN 이용방법

SELECT distinct P1.CART_ID
    FROM CART_PRODUCTS P1
    CROSS JOIN CART_PRODUCTS P2
    ON P1.CART_ID = P2.CART_ID AND P1.NAME = 'Milk' AND P2.NAME = 'Yogurt'