


SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(USER_ID) >= 2 AND COUNT(PRODUCT_ID) >= 2 -- 언급된 user_id 랑 product_id가 두개 이상 된 거
ORDER BY USER_ID, PRODUCT_ID DESC